# action.yml
name: 'publish-confluence'
description: 'Publish sphinx docs to atlassian confluence cloud'
inputs:
  username:
    description: 'email of user used to access confluence'
    required: true
  apitoken:
    description: 'apitoken to auth with confluence. Obtain one from https://id.atlassian.com/manage/api-tokens'
    required: true
  docsdir: './docs/source/'
    description: 'directory in the repo where the docs are located'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
